# SPDX-FileCopyrightText: 1998 Argonne National Laboratory
#
# SPDX-License-Identifier: EPICS

TOP=../..
include $(TOP)/configure/CONFIG

DB += table.db
DB += tableCsv.db

include $(TOP)/configure/RULES

